// Mock API service for when database is disconnected
// Returns mock data that matches the Prisma schema structure

export const mockUsers = [
  {
    id: "1",
    username: "admin",
    name: "Admin User",
    password: "admin123",
    role: "admin",
    vaultPoints: 1000,
    rank: 1,
    itemsUploaded: 0,
    claimsSubmitted: 0,
    attendanceCount: 0,
    serviceCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    username: "johndoe",
    name: "John Doe",
    password: "password123",
    role: "user",
    vaultPoints: 450,
    rank: 4,
    itemsUploaded: 3,
    claimsSubmitted: 1,
    attendanceCount: 8,
    serviceCount: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    username: "tomanderson",
    name: "Tom Anderson",
    password: "password123",
    role: "volunteer",
    vaultPoints: 500,
    rank: 2,
    itemsUploaded: 0,
    claimsSubmitted: 0,
    attendanceCount: 18,
    serviceCount: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    username: "sarahjohnson",
    name: "Sarah Johnson",
    password: "password123",
    role: "user",
    vaultPoints: 380,
    rank: 5,
    itemsUploaded: 2,
    claimsSubmitted: 0,
    attendanceCount: 5,
    serviceCount: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    username: "michaelchen",
    name: "Michael Chen",
    password: "password123",
    role: "user",
    vaultPoints: 420,
    rank: 3,
    itemsUploaded: 5,
    claimsSubmitted: 2,
    attendanceCount: 10,
    serviceCount: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    username: "emilyrodriguez",
    name: "Emily Rodriguez",
    password: "password123",
    role: "volunteer",
    vaultPoints: 520,
    rank: 2,
    itemsUploaded: 1,
    claimsSubmitted: 0,
    attendanceCount: 20,
    serviceCount: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    username: "davidpark",
    name: "David Park",
    password: "password123",
    role: "user",
    vaultPoints: 360,
    rank: 6,
    itemsUploaded: 1,
    claimsSubmitted: 0,
    attendanceCount: 3,
    serviceCount: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    username: "jenniferwilliams",
    name: "Jennifer Williams",
    password: "password123",
    role: "volunteer",
    vaultPoints: 480,
    rank: 2,
    itemsUploaded: 0,
    claimsSubmitted: 0,
    attendanceCount: 15,
    serviceCount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockItems = [
  {
    id: "1",
    title: "Black Leather Wallet",
    imageUrl: "/black-leather-wallet.png",
    category: "accessories",
    color: "black",
    location: "main-desk",
    dateFounded: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Brown leather wallet with card slots",
    status: "available",
    uploadedBy: "john",
    donationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    uniqueMarkings: "Initials JD on back",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Blue Umbrella",
    imageUrl: "/blue-umbrella.jpg",
    category: "weather",
    color: "blue",
    location: "entrance",
    dateFounded: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Compact blue umbrella with wooden handle",
    status: "available",
    uploadedBy: "sarah",
    donationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    uniqueMarkings: "Small tear on left side",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Silver Wristwatch",
    imageUrl: "/silver-wristwatch.png",
    category: "accessories",
    color: "silver",
    location: "main-desk",
    dateFounded: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Men's silver analog watch, working condition",
    status: "available",
    uploadedBy: "michael",
    donationDeadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    uniqueMarkings: "Brand: Seiko, scratches on crystal",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockClaims = [
  {
    id: "1",
    itemId: "1",
    userId: "3",
    proofImages: ["/wallet-receipt.jpg"],
    status: "pending",
    claimedAt: new Date(),
    releaseNotes: null,
    releasedBy: null,
    releasedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockLocations = [
  {
    id: "1",
    name: "Main Desk",
    code: "main-desk",
    description: "Front reception desk",
    capacity: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Entrance",
    code: "entrance",
    description: "Building entrance area",
    capacity: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Storage Room",
    code: "storage",
    description: "Main storage facility",
    capacity: 200,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockPlaybooks = [
  {
    id: "1",
    title: "Item Processing Guide",
    content: "Step-by-step guide for processing found items",
    category: "operations",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Claim Verification",
    content: "How to verify claims for lost items",
    category: "claims",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockAuditLogs = [
  {
    id: "1",
    userId: "1",
    action: "ITEM_UPLOADED",
    details: "User uploaded black leather wallet",
    timestamp: new Date(),
    ipAddress: "192.168.1.1",
  },
  {
    id: "2",
    userId: "3",
    action: "CLAIM_SUBMITTED",
    details: "User submitted claim for wallet",
    timestamp: new Date(Date.now() - 60000),
    ipAddress: "192.168.1.50",
  },
]
